### ISSUE TITLE
Use presentation compiler for code assist

### ISSUE THREAD

**Issue by dragos** [spark-notebook/spark-notebook#142]
It'd be great to hook the Scala presentation compiler in the kernel, so completions, errors-as-you-type, hovers, etc. can be much more precise. The REPL has very limited completion capabilities.

This is something I could have a look at down the line, I'm just writing this down to check if this has been considered and discarded for some reason.

**Comment by andypetrella** [comment]
Hello Iulian!
(I put here the reference to the document: [Scala presentation compiler](http://scala-ide.org/docs/dev/architecture/presentation-compiler.html))

That would be indeed interesting to hook up the current completion mechanism with this one! It hasn't yet been discussed, so thanks for bringing it to the table.

Questions I have:
* since the notebook will most of the case be something remote, I guess that the errors-as-you-type will be hard since a lot (gut feeling) will be necessary for that?
* it'll be used for the presentation (the hover, type info, better completions and so forth... I **LOVED** that) hence we'll still use the Spark loop and compiler for the task to bind new variables right? The thing is that the spark repl has done so much w.r.t closure serialization that we need⁽*⁾ to keep

For the rest, I repeat myself, I'd LOVED to have this kind of functionality in notebooks. And if you could have a look at that, I'll be very glad if I could give you some hands (if only ever you need it ^^)

⁽*⁾will be easy to

**Comment by dragos** [comment]
Hi Andy,

Glad you're interested in this!

You're right about "errors as you type". In Eclipse we use a "quiescence" period of 500ms before we ask the compiler to type-check, and I think that we should be able to pull the same trick here (this would be async, so error annotations will arrive *eventually*). The rest of code "intelligence" should be fairly straightforward.

I have another idea that would need a lot more thinking, but I think it would give us even more leverage. Here's the gist: instead of feeding the REPL object with chunks of code, have a more "global" approach: chunks are inserted into a "skeleton" object and evaluated top-down or incrementally. This way, some "TaksNotSerializableExceptions" we sometimes see (that are artefacts of the way the REPL encodes each chunk as a `iw` nested object) will go away. As I said, this is more long-term and high-risk, so I need to prototype it first (but it would follow the ideas we use in the Scala Worksheet implementation).

**Comment by andypetrella** [comment]
Agreed!

The second part sounds really promising, it should also ameliorate the performance of spark-repl I guess (like serializing only what's really necessary, without closing almost everything).

And indeed, although the repl is a very powerful tool, the `iwC` (in Spark) stuffs are quite boring, specially when you wanna work with implicits or Kryo (atm).

You're the best to propose a lean way to move forward, do you see a quick win (`hover` providing contextual information would be just awesome)?
So we create a dedicated entry for it and with reference it to this one? → Would like to keep this thread live for discussions around _presentation_

**Comment by andypetrella** [comment]
Yop @dragos, I was wondering if you would be available/okay for a quick hangout on this one?
I really like the idea and would like to have more details on what (and how) could be done :-D.

**Comment by dragos** [comment]
Sure! Next week would work better, I'm pretty tight until then.

**Comment by andypetrella** [comment]
Okido :-D.
What about Thu 16? Are you in Swiss or SFO (or ???) ?

**Comment by dragos** [comment]
I'm in transit to Switzerland. Sorry, I meant the week of 20. Would that work?

**Comment by andypetrella** [comment]
okido, Tuesday 21th ? → andy.petrella @ gmail . com so we can arrange that easily

**Comment by andypetrella** [comment]
general info
----------------

After some discussion it appears that the usage of the presentation compiler (PC) will bring a lot of stability and enable new features wrt interaction with the code.

This PC works as a server back-ended by a requests queue which acts on a set of source files.
We can ask it for completions, errors, type checkers and so forth.

Note that it's single threaded, it'll be a problem when the session will be shared across viewers (see #148), but we'll can handle that on the server by created an actor for each session that will lineralize the incoming requests into a stream sent to the PC.

It would be also possible to answer with the scaladoc but then we'll need to include the sources as well. _This is delayed at first._


first steps
-------------
There are two interesting features that could quickly be enabled. Here they are:
* functions/classes parameters: hitting `SHIFT+TAB` sends requests to the server about the current function or class. The idea is to use the PC for that

* error handling: the code is sent to the PC and if there is a problem, we flag the line (or the cell) as errors (with an icon) which reacts on hover by popping the error message


how to
---------
Since the PC works on sources files, we need to simulate that since the notebook is a bunch of cells.
There are two obvious ways to achieve that:
- create a source file somewhere that will keep all cells merged. So that, when a request comes from a cell we'll need to compute the correct line offset (based on the previous cells)
- create as many source files as there are cells. In this case, we'll need to keep track of the relations... this can be hard

Another way to do that would be to **workaround** the problems by using the JSON representation of the notebook. In that case, each request will have first to save the notebook before issuing the request to the PC. It's tricky/hackish but could do the job as a very first step.

So the flow would be:
* `SHIFT-TAB` is entered
* the javascript client saves the notebook and register to the save success event
* the javascript client sends the request to the server
* the server forward the request to the PC
* the PC receives the position in the cell and the cell (to check), 
  * reads the JSON notebook representation,       **(→could be done at save time)**
  * updates a temp source file (?) representing it  **(→could be done at save time)**
  * and computes the offset based on previous cells
  * does its magic

## Pointers
The `SHIFT+TAB` control is handled this way.

On the client side, the [tooltip](https://github.com/andypetrella/spark-notebook/blob/master/public/ipython/notebook/js/tooltip.js#L100) asks the server for some contextual information.

On the server side, the [WS hanlder](https://github.com/andypetrella/spark-notebook/blob/master/app/notebook/WebSocketKernelActor.scala#L58) catches the request and forward it to the repl (the calculator wraps it).
So the [calculator](https://github.com/andypetrella/spark-notebook/blob/master/app/notebook/CalcWebSocketService.scala#L51) receives the session request from a single execution [actor](https://github.com/andypetrella/spark-notebook/blob/master/app/notebook/CalcWebSocketService.scala#L91) which will [send](https://github.com/andypetrella/spark-notebook/blob/master/app/notebook/CalcWebSocketService.scala#L137) the response back to the WS. 

Based on the above, the [ReplCalculator (2.10 here)](ReplCalculator) takes the charge to process the request [by delegating](https://github.com/andypetrella/spark-notebook/blob/master/modules/kernel/src/main/scala-2.10/notebook/ReplCalculator.scala#L361) the responsibility to the [Repl](https://github.com/andypetrella/spark-notebook/blob/master/modules/spark/src/main/scala_2.10/spark-1.3.0/notebook/kernel/Repl.scala#L298).

**IMPORTANT**: the actor `ReplCalculator` is deployed on the remote process running Spark. That is the one that really run a REPL. 

Hence the **presentation compiler** should be started for this remote process, meaning that we'll have one PC per remote process/notebook.

@dragos this is where I guess you have a way better knowledge that I could have.
It would be very good already if you could find some time to see how the PC could be added there.
Then I can help for the integration if needed.
WDYT?

**Comment by dragos** [comment]
@andypetrella this are very useful pointers, and sorry for the long silence. I'll spend some time on this today and tomorrow, and I'll let you know how far I got.

**Comment by andypetrella** [comment]
No problemo, no pressure :-D

Thanks for anything you'll can do ^^

**Comment by cbvoxel** [comment]
Hey Andy,
has anything happened in this direction already? You pointed me into this direction, and now that I made first contact with the PC I wonder if this could be pulled off, even if it's a humble first shot?
Did I understand you correctly, that you would use the existing completion approach/mechanism but instead of using the REPL use the PC?

Just for reference, another interesting link is 
http://ensime.blogspot.fr/2010/08/building-ide-with-scala-presentation.html

**Comment by andypetrella** [comment]
Hey @cbvoxel, this would be super cool, because I know that @dragos is super busy at the moment.

The idea is to use indeed the PC for completion stuffs, first only even functions parameters and better completion (because the REPL alone sucks a bit at that).

I described in the issue some entrypoints and things to change, however there is one thing I need to say.
The REPL integration is not at best at the moment, there is a lot of duplication per spark version (and it's more or less needed to have one per version, but still code duplication) there is a ticket for that #205 

So, in order to decouple those, what about first integrate these stuffs in spark 1.5, scala 2.10 only first?
Then we'll see what we'll need to do to deduplicate things?

**Comment by dragos** [comment]
Have a look at https://github.com/scala/scala/pull/4725  If this makes it into 2.11.8, we'll have much better completions out of the box.

**Comment by dragos** [comment]
@andypetrella, the Spark REPL in 2.11 is no longer a fork, it just overrides a couple of methods. Ideally Spark Notebook shouldn't need to fork either, and then REPL improvements in completion, like the one mentioned above, would come for free.

**Comment by andypetrella** [comment]
@dragos all great news!!!
So let's wait for spark to switch to scala 2.11.8 (2.11.6 atm).

On the other side, the 2.10 one, we still have to do something, because lot of people are still using it...
Do you thing you could support, I guess time to time, @cbvoxel for questions?

**Comment by cbvoxel** [comment]
@andypetrella I have "injected" the PC into the REPLCalculator, so that it takes the pc and not the repl. It kind of works, which means that I get a lot of completions, but not all. For example, I am missing all the collection methods (map, filter, foreach, etc.) I wonder why they aren't there? Do I need to include a couple of imports? If yes, which ones?

Also to get parameter information of methods it would be helpful to get the parameter names. Instead all I get are generic names as x$1, and so on. Is there a way to improve that?

To have richer functionality one should probably add functionality on the js side. As I am definitly not a js guy, I am kinda stuck. One nice feature to have would be to get type info when pressing Ctrl and hovering over a symbol. How would I do this?

**Comment by dragos** [comment]
Have a look at https://github.com/dragos/spark-notebook/commit/2ffd9f63a07d68683faae161c1d0b7e854c60356, I added "Inspect", which is sort of hover (I think it's called by pressing TAB). Not sure if the code is yet in the compiler, see the PR I linked to on scala/scala. Hope this helps!

**Comment by andypetrella** [comment]
@cbvoxel @dragos great to read that this is moving forward (and fast :-D).

I'm okay to move forward bit by bit, I mean the best is to have a solution quick then applying patches to make it more and more awesome (in contrary of waiting for the perfection, if you know what I mean).
So don't mind the _how to_ for now. It'll remain here for further steps.

Regarding your points, what about writing a notebook or some doc about (showing) what work and what doesn't work? We can also have an hangout, however, I'm gonna have one of my hectic'est week ever, so it's gonna be for the next week if you can wait for that. Then I'll can help you out in the JS too (if I can).

@dragos your fork looks good, is it normal it uses `SparkPresentationCompilerCompleter` ? I mean, where is this guy :-P?

Thanks a lot gentlemen for the work and help!

**Comment by dragos** [comment]
@andypetrella it should probably be now just `PresentationCompilerCompleter`, see scala/scala#4725 that was just merged.

**Comment by andypetrella** [comment]
@dragos aaaaah that's cool! Getting there, looks like

**Comment by frbayart** [comment]
> andypetrella added a commit that referenced this issue on 3 Oct 2015
