### ISSUE TITLE
Docker: missing wget

### ISSUE THREAD

**Issue by benqua** [spark-notebook/spark-notebook#734]
While running the example "Simple ML in Spark.snb", I get an exception while running:
`:sh wget https://s3-eu-west-1.amazonaws.com/spark-notebook-data/closes.csv -O /tmp/closes.csv`

 `java.io.IOException: Cannot run program "wget": error=2, No such file or directory
  at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
  at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:69)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:113)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:129)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:103)
  ... 63 elided
Caused by: java.io.IOException: error=2, No such file or directory
  at java.lang.UNIXProcess.forkAndExec(Native Method)
  at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
  at java.lang.ProcessImpl.start(ProcessImpl.java:130)
  at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
  ... 67 more`

This happens while running:
`sudo  docker run -p 9001:9001 andypetrella/spark-notebook:0.7.0-scala-2.11.8-spark-2.0.1-hadoop-2.7.2`

By the way, the spark generator documentation asks to map port 9000 while the play server run on port 9001 (http://spark-notebook.io/dl/docker/0.7.0/2.11/2.0.1/2.7.2/false/true says  docker run -p 9000:9000 andypetrella/spark-notebook:0.7.0-scala-2.11.8-spark-2.0.1-hadoop-2.7.2)

**Comment by andypetrella** [comment]
warf, damn it... need to add to the Dockerfile then (don't know how yet though ^^)

I'll update the generator too

**Comment by benqua** [comment]
I don't know exactly where the Docker file is, and which base image is used, but adding wget shouldn't be more than something like:
RUN apt-get install wget

**Comment by andypetrella** [comment]
I added them to the docker configuration, however, will be only available on master :-(

**Comment by dportabella** [comment]
I tried getting the last version, but `wget` is not yet included.
`docker run -p 9001:9001 andypetrella/spark-notebook:0.7.0-scala-2.11.8-spark-2.1.0-hadoop-2.7.3
`
You mentioned that you added it to the master. How do we get the master docker image?

I am aware you propose to [download the file using Scala](https://github.com/andypetrella/spark-notebook/issues/680#issuecomment-238496099) as alternative, but I'd prefer avoiding that.

Otherwise, is it possible to install `wget` from within the notebook? I've tried with `:sh apt-get install -f wget` but it does not work. Also, I didn't find the Dockerfile in [hub docker](https://hub.docker.com/r/andypetrella/spark-notebook/). Is there a reason to hide it? Also, I tried running bash, but it says invalid application: `docker run -ti andypetrella/spark-notebook:0.7.0-scala-2.11.8-spark-2.1.0-hadoop-2.7.3 bash`. Isn't it a standard ubuntu image?

**Comment by dportabella** [comment]
oh, i got it, the equivalent to the Dockerfile is here: https://github.com/andypetrella/spark-notebook/blob/master/project/DockerProperties.scala

and to install wget from within the notebook:
`:sh apt-get install -y wget`

**Comment by frbayart** [comment]
Hi ,

we use "sbt docker:publish" to generate the Docker image it's why we don't have a real Dockerfile (we hide nothing ;p) and yes you can have more information in DockerProperties and in : 
https://github.com/andypetrella/spark-notebook/blob/master/build.sbt#L37

The base image is debian:jessie-backports

**Comment by frbayart** [comment]
wget should be installed too the latest version https://github.com/andypetrella/spark-notebook/blob/master/project/DockerProperties.scala#L18

**Comment by dportabella** [comment]
thx for the reply, @frbayart :)
so, in order to use the latest version, we need to download the project and use `sbt docker:publish`, right? we cannot simply use `docker run -p 9001:9001 andypetrella/spark-notebook:0.7.0-scala-2.11.8-spark-2.1.0-hadoop-2.7.3` (or with some other tag) because it is not yet in hub docker, correct? do you plan to publish it to hub docker sometime soon?

**Comment by frbayart** [comment]
@dportabella  you can use `sbt docker:publishLocal` to publish it in your local `docker images`

I'm chehcking with Andy to generate a new images on Docker hub
