### ISSUE TITLE
Is there support/documentation on running with google cloud platform dataproc ?

### ISSUE THREAD

**Issue by ajkl** [spark-notebook/spark-notebook#906]

**Comment by vidma** [comment]
currently no, but cluster setup is almost same as for Spark Apps (just see spark docs!).

and, usually, setup is rather standard depending on a Hadoop/Spark cluster manager (you need YARN or Mesos -  just check docs for google cloud itself and your requirements on what works better for you).


see https://github.com/spark-notebook/spark-notebook/blob/master/docs/clusters_clouds.md for a starting point, and feel free to contribute (make a `Pull Request` for the docs) any specifics/issues you discover on the way.

P.S. make sure to compile the same version of Mesos/YARN or other libs as the ones in your cluster if you are willing to use native libs (i.e. if you are going to include the default hadoop libs shipped with the cluster if you're going to run spark jobs on the cluster mode [instead of local mode] ).
