### ISSUE TITLE
Error loading notebook, not found

### ISSUE THREAD

**Issue by Eddiechiu** [spark-notebook/spark-notebook#939]
![_20180129144856](https://user-images.githubusercontent.com/16081098/35497123-d77b880a-0503-11e8-9c77-ec5fa5a6111e.png)

When I open a .snb file I used to edit, it shows that, how can I fix it. I didn't do any changes.

**Comment by Eddiechiu** [comment]
![image](https://user-images.githubusercontent.com/16081098/35501532-35f342b8-0515-11e8-9135-fd532f0060b1.png)

all my .snb files are in another file, named notebooks, which is out of the main path of spark-notebook folder. How can I change the path to spark-notebook/notebooks ?
Thank you so much!

**Comment by andypetrella** [comment]
Hello, you can do this per configuration: https://github.com/spark-notebook/spark-notebook/blob/master/conf/application.conf#L55

You can thus override the property in your configuration file or set the var env before launching the notebook sever

hth
andy

**Comment by Eddiechiu** [comment]
thank you andy~
![_20180129172017](https://user-images.githubusercontent.com/16081098/35502788-107b02f6-0519-11e8-82bb-72d0305958a3.png)

but my conf file seems the same as the one you show me.
where can I set var env ?

**Comment by andypetrella** [comment]
like this
```
export NOTEBOOKS_DIR=<your notebooks dir>
./bin/spark-notebook
```

**Comment by frbayart** [comment]
you can try:
`NOTEBOOKS_DIR=YOUR_PATH ./bin/spark-notebook`
or
`NOTEBOOKS_DIR=YOUR_PATH sbt run`

to have a permanent NOTEBOOKS_DIR set you need to edit your .bash_profile or equivalent if you use another shell.

**Comment by Eddiechiu** [comment]
![image](https://user-images.githubusercontent.com/16081098/35509815-891c9af4-04aa-11e8-8a4e-786dfc6bad27.png)
Do you mean this?
But it still doesn't work. 
my spark-notebook path is ~/Downloads/spark-notebook
several days before, my .snb files are stored in ~/Downloads/spark-notebook/notebooks
and I can open and edit them
today, I cannot open them anymore, it shows "error loading notebook  not found". 
And it seems that the files are also stored in ~/Downloads/notebooks
I don't know how it happens...

**Comment by andypetrella** [comment]
This variable must point to the `notebooks` folder instead of the binary
Also I wouldn’t use `~`


Do you start it from the parent folder of `bin`? Like `bin/spark-notebook`

htt
Andy

On 29 January 2018 at 13:17:49, Derong Qiu (notifications@github.com) wrote:

[image: image]
<https://user-images.githubusercontent.com/16081098/35509815-891c9af4-04aa-11e8-8a4e-786dfc6bad27.png>
Do you mean this?
But it still doesn't work.
my spark-notebook path is ~/Downloads/spark-notebook
several days before, my .snb files are stored in
~/Downloads/spark-notebook/notebooks
and I can open and edit them
today, I cannot open them anymore, it shows "error loading notebook not
found".
And it seems that the files are also stored in ~/Downloads/notebooks
I don't know how it happens...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/spark-notebook/spark-notebook/issues/939#issuecomment-361228325>,
or mute the thread

**Comment by Eddiechiu** [comment]
I see !!! I used to start in ./bin, like:
spark-notebook/bin$ sudo bash spark-notebook

if change to:
spark-notebook$ sudo ./bin/spark-notebook
the problem is solved, thank you andy !!! Also thanks to frbayart  =D
